#!/bin/bash


function setup_guts_dashboard {
    sudo apt-get install -y guts-dashboard
}

function setup_guts_dashboard_source {
    # git clone https://github.com/aptira/guts-dashboard ${STACK_DIR}/guts-dashboard
    # sudo -H pip install -e ${STACK_DIR}/guts-dashboard

    # ln -s ${STACK_DIR}/guts-dashboard/gutsdashboard/local/_50_guts.py ${STACK_DIR}/horizon/openstack_dashboard/local/enabled/_50_guts.py
    ln -s ${STACK_DIR}/guts-dashboard/gutsdashboard/local/_5010_guts_services.py ${STACK_DIR}/horizon/openstack_dashboard/local/enabled/_5010_guts_services.py
    ln -s ${STACK_DIR}/guts-dashboard/gutsdashboard/local/_5020_guts_resources.py ${STACK_DIR}/horizon/openstack_dashboard/local/enabled/_5020_guts_resources.py
    ln -s ${STACK_DIR}/guts-dashboard/gutsdashboard/local/_5030_guts_migrations.py ${STACK_DIR}/horizon/openstack_dashboard/local/enabled/_5030_guts_migrations.py
}
