#!/bin/bash

function setup_horizon {
    KEYSTONE_HOST=$1

    sudo apt-get install -y openstack-dashboard

    # Change local_settings to use version 3.
    sudo bash -c 'cat << EOF >> /etc/openstack-dashboard/local_settings.py

OPENSTACK_API_VERSIONS = {
    "identity": 3
}
EOF'

    if [[ -n ${KEYSTONE_HOST} ]]; then
        echo "Setting up horizon to use a remote Keystone Host"
        sudo sed -i "s@^OPENSTACK_HOST.*@OPENSTACK_HOST = '${KEYSTONE_HOST}'@" /etc/openstack-dashboard/local_settings.py
    fi

    sudo service apache2 restart
}


function setup_horizon_source {
    git clone https://github.com/openstack/horizon.git -b stable/mitaka /opt/stack/horizon
    cd /opt/stack/horizon
    pip install -e /opt/stack/horizon
    cp openstack_dashboard/local/local_settings.py.example openstack_dashboard/local/local_settings.py
    cat >> openstack_dashboard/local/local_settings.py << EOF

OPENSTACK_API_VERSIONS = {
    "identity": 3
}
EOF
    python /opt/stack/horizon/manage.py runserver 0.0.0.0:8888

    git clone https://github.com/aptira/guts-dashboard.git  /opt/stack/guts-dashboard
    sudo -H pip install -e /opt/stack/python-gutsclient
    sudo -H pip install -e /opt/stack/guts-dashboard


}
