#!/bin/bash

function setup_horizon {
    KEYSTONE_HOST=$1

    sudo apt-get install -y openstack-dashboard

    # Change local_settings to use version 3.
    sudo bash -c 'cat << EOF >> /etc/openstack-dashboard/local_settings.py

OPENSTACK_API_VERSIONS = {
    "identity": 3
}
EOF'

    if [[ -n ${KEYSTONE_HOST} ]]; then
        echo "Setting up horizon to use a remote Keystone Host"
        sudo sed -i "s@^OPENSTACK_HOST.*@OPENSTACK_HOST = '${KEYSTONE_HOST}'@" /etc/openstack-dashboard/local_settings.py
    fi

    sudo apt-get purge -y openstack-dashboard-ubuntu-theme
    sudo service apache2 restart
}

function install_horizon_source {
    sudo mkdir -p ${STACK_DIR} && sudo chown -R ${USER}:${USER} ${STACK_DIR}
    git clone https://github.com/openstack/horizon ${STACK_DIR}/horizon
    sudo -H pip install -e ${STACK_DIR}/horizon
    if [ -r ${STACK_DIR}/horizon/openstack_dashboard/local/local_settings.py ]; then
        rm ${STACK_DIR}/horizon/openstack_dashboard/local/local_settings.py
    fi
    cp ${STACK_DIR}/horizon/openstack_dashboard/local/local_settings.py.example ${STACK_DIR}/horizon/openstack_dashboard/local/local_settings.py
    sudo bash -c 'cat << EOF >> /opt/stack/horizon/openstack_dashboard/local/local_settings.py

ALLOWED_HOSTS = ["*"]
OPENSTACK_API_VERSIONS = {
    "identity": 3
}
EOF'

}

function setup_horizon_source {
    install_horizon_source
}
