#!/bin/bash

function setup_horizon {
    KEYSTONE_HOST=$1

    sudo apt-get install -y openstack-dashboard

    # Change local_settings to use version 3.
    sudo bash -c 'cat << EOF >> /etc/openstack-dashboard/local_settings.py

OPENSTACK_API_VERSIONS = {
    "identity": 3
}
EOF'

    if [[ -n ${KEYSTONE_HOST} ]]; then
        echo "Setting up horizon to use a remote Keystone Host"
        sudo sed -i "s@^OPENSTACK_HOST.*@OPENSTACK_HOST = '${KEYSTONE_HOST}'@" /etc/openstack-dashboard/local_settings.py
    fi

    sudo apt-get purge -y openstack-dashboard-ubuntu-theme
    sudo service apache2 restart
}
