#!/bin/bash

function setup_neutron_database {
    mysql -u root -p${PASSWORD} -e "CREATE DATABASE neutron;"
    mysql -u root -p${PASSWORD} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '${PASSWORD}'; ";
    mysql -u root -p${PASSWORD} -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '${PASSWORD}'; "
}

function populate_keystone_neutron {

    source ${OPENRC_DIR}/admin

    openstack user create --domain default --password ${PASSWORD} neutron
    openstack role add --project service --user neutron admin
    openstack service create --name neutron --description "OpenStack Image" network
    openstack endpoint create --region RegionOne network public http://${IP_ADDR}:9696
    openstack endpoint create --region RegionOne network internal http://${IP_ADDR}:9696
    openstack endpoint create --region RegionOne network admin http://${IP_ADDR}:9696
}

function install_neutron_components {
    # sudo apt-get install -y neutron-server neutron-plugin-ml2 neutron-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent
    # sudo apt-get -y install neutron-plugin-openvswitch neutron-plugin-openvswitch-agent
    sudo apt-get -y install neutron-server neutron-plugin-ml2 neutron-dhcp-agent neutron-l3-agent neutron-metadata-agent openvswitch-switch
    sudo apt-get -y install neutron-plugin-openvswitch neutron-openvswitch-agent
}

function configure_neutron_server {
    sudo bash -c "cat << EOF > /etc/neutron/neutron.conf
[DEFAULT]
core_plugin = ml2
service_plugins = router
allow_overlapping_ips = True
rpc_backend = rabbit
auth_strategy = keystone
notify_nova_on_port_status_changes = True
notify_nova_on_port_data_changes = True

[keystone_authtoken]
auth_uri = http://${IP_ADDR}:5000
auth_url = http://${IP_ADDR}:35357
memcached_servers = ${IP_ADDR}:11211
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = neutron
password = ${PASSWORD}

[database]
connection = mysql+pymysql://neutron:${PASSWORD}@localhost/neutron

[oslo_messaging_rabbit]
rabbit_host = ${IP_ADDR}
rabbit_userid = openstack
rabbit_password = ${PASSWORD}

[nova]
auth_url = http://${IP_ADDR}:35357
auth_type = password
project_domain_name = default
user_domain_name = default
region_name = RegionOne
project_name = service
username = nova
password = ${PASSWORD}

EOF"
}

function configure_ml2_plugin {

    sudo bash -c "cat << EOF > /etc/neutron/plugins/ml2/ml2_conf.ini
[ml2]
type_drivers = flat,vlan
tenant_network_types = vlan,flat
mechanism_drivers = openvswitch
extension_drivers = port_security

[ml2_type_flat]
# flat_networks = provider
flat_networks = External

[ml2_type_vlan]
network_vlan_ranges=Intnet1:100:200

[ml2_type_gre]

[ml2_type_vxlan]

[securitygroup]
firewall_driver=neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
enable_security_group=True
#enable_ipset = True

[ovs]
bridge_mappings=External:br-ex,Intnet1:br-eth1

EOF"
}

function configure_metadata_agent {
    sudo bash -c "cat << EOF > /etc/neutron/metadata_agent.ini
[DEFAULT]
nova_metadata_ip = 192.168.33.2
metadata_proxy_shared_secret = ${PASSWORD}
EOF"

}

function configure_dhcp_agent {
    sudo bash -c "cat << EOF > /etc/neutron/dhcp_agent.ini
[DEFAULT]
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq
enable_isolated_metadata = True
dnsmasq_dns_servers = 8.8.8.8

EOF"
}

function configure_l3_agent {
    sudo bash -c "cat << EOF > /etc/neutron/l3_agent.ini
[DEFAULT]
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
use_namespaces = True

EOF"
}

function configure_nova_for_neutron {
    sudo bash -c "cat << EOF >> /etc/nova/nova.conf

[neutron]
url = http://${IP_ADDR}:9696
auth_url = http://${IP_ADDR}:35357
auth_type = password
project_domain_name = default
user_domain_name = default
region_name = RegionOne
project_name = service
username = neutron
password = ${PASSWORD}
service_metadata_proxy = True
metadata_proxy_shared_secret = ${PASSWORD}

EOF"
}

function configure_neutron {
    configure_neutron_server
    configure_ml2_plugin
    configure_metadata_agent
    configure_dhcp_agent
    configure_l3_agent
}

function populate_database {
    sudo su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
}

function restart_neutron_services {
    sudo service nova-api restart
    sudo service neutron-server restart
    # sudo service neutron-linuxbridge-agent restart
    sudo service neutron-plugin-openvswitch-agent restart
    sudo service neutron-dhcp-agent restart
    sudo service neutron-metadata-agent restart
    sudo service neutron-l3-agent restart
}

function configure_compute_for_neutron {
    sudo apt-get install -y neutron-linuxbridge-agent
    sudo service nova-compute restart
    sudo service neutron-linuxbridge-agent restart
}

function setup_neutron {
    # setup_neutron_database
    # populate_keystone_neutron
    # install_neutron_components
    configure_neutron
    populate_database
    restart_neutron_services
    # configure_compute_for_neutron
}
