#!/bin/bash

function install_cloud_keyring {
    sudo apt-get install -y ubuntu-cloud-keyring
    sudo apt-add-repository 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main'
    sudo apt-get update
}

function install_mysql {
    # Install mysql
    echo "mariadb-server mysql-server/root_password password ${PASSWORD}" | sudo debconf-set-selections
    echo "mariadb-server mysql-server/root_password_again password ${PASSWORD}" | sudo debconf-set-selections

    sudo apt-get -y install mariadb-server python-pymysql

    # Configure your mysql installation
    sudo bash -c 'cat << EOF > /etc/mysql/conf.d/openstack.cnf
[mysqld]
default-storage-engine = innodb
innodb_file_per_table
max_connections = 4096
collation-server = utf8_general_ci
character-set-server = utf8
EOF'

    # Restart and setup secure installation
    sudo service mysql restart

    # TODO: Automate this
    # mysql_secure_installation

    # Verify Mysql Installation
    mysql -u root -p${PASSWORD} -e "SHOW DATABASES;"
}

function install_rabbitmq {
    ### Setup RabbitMQ
    sudo apt-get -y install rabbitmq-server

    sudo rabbitmqctl add_user openstack ${PASSWORD}
    sudo rabbitmqctl set_permissions openstack ".*" ".*" ".*"

    sudo rabbitmqctl list_users
}

function install_clients {
    sudo apt-get install -y python-openstackclient
}
