#!/bin/bash

function install_openstack_packages {
    if is_ubuntu; then
        ubuntu_install_package ubuntu-cloud-keyring
        sudo apt-add-repository 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main'
    elif is_fedora; then
        fedora_install_package centos-release-openstack-mitaka
    fi
    update
    upgrade
}

function install_mysql {
    # Install mysql
    if is_ubuntu; then
        echo "mariadb-server mysql-server/root_password password ${PASSWORD}" | sudo debconf-set-selections
        echo "mariadb-server mysql-server/root_password_again password ${PASSWORD}" | sudo debconf-set-selections
    fi

    install_package mariadb mariadb-server

    # Restart and setup secure installation
    is_ubuntu && sudo service mysql restart || sudo systemctl enable mariadb.service && sudo systemctl start mariadb.service

    if is_ubuntu; then
        ubuntu_install_package python-pymysql
    elif is_fedora; then
        mysqladmin -u root --password='' password $PASSWORD
        fedora_install_package python2-PyMySQL
    fi

    # Configure your mysql installation
    sudo bash -c 'cat << EOF > /etc/mysql/conf.d/openstack.cnf
[mysqld]
default-storage-engine = innodb
innodb_file_per_table
max_connections = 4096
collation-server = utf8_general_ci
character-set-server = utf8
EOF'


    # TODO: Automate this
    # mysql_secure_installation

    # Verify Mysql Installation
    mysql -u root -p${PASSWORD} -e "SHOW DATABASES;"
}

function install_rabbitmq {
    ### Setup RabbitMQ
    install_package rabbitmq-server

    is_ubuntu && sudo service rabbitmq-server restart || sudo systemctl enable rabbitmq-server.service && sudo systemctl start rabbitmq-server.service

    sudo rabbitmqctl add_user openstack ${PASSWORD}
    sudo rabbitmqctl set_permissions openstack ".*" ".*" ".*"

    sudo rabbitmqctl list_users
}

function install_clients {
    install_package python-openstackclient
}
